package edu.incense.android.datatask.model;

public enum TaskType {
    NULL, 
    AccelerometerSensor, 
    GyroscopeSensor, 
    AudioSensor, 
    SurveySensor,
    BluetoothSensor, 
    GpsSensor, 
    CallSensor, 
    StateSensor, 
    WifiScanSensor, 
    WifiConnectionSensor, 
    AccelerometerMeanFilter, 
    DataSink, 
    AudioSink, 
    SessionTrigger, 
    SurveyTrigger, 
    Trigger,
    ShakeFilter, 
    BluetoothConnectionSensor,
    NfcSensor,
    WifiTimeConnectedFilter,
    StopTrigger,
    TimerSensor,
    PowerConnectionSensor,
    MovementFilter,
    FalseTimerFilter,
    MovementTimeFilter
}
